### ISSUE TITLE
闪退bug

### ISSUE THREAD

**Issue by XJChenYang** [letr007/CCTVVideoDownloader#11]
更新了新版本后，打开软件选中节目单就闪退，系统是win11 22H2版本

**Comment by letr007** [comment]
能否提供截图？我记得新版本没有导入节目单的功能了啊

**Comment by XJChenYang** [comment]
![19](https://github.com/letr007/CCTVVideoDownloader/assets/61348687/94107950-09eb-4406-a8ff-ffc957d003a2)
才看到回复，抱歉录了个gif，双击那个节目就闪退，好像界面也没有出现具体视频，然后程序选项中有个导入视频链接选项也没用，复制链接导入没反应

**Comment by letr007** [comment]
这种情况看起来可能是由于访问央视网的API失败导致的，项目的错误处理机制尚不完善，如果报错即会退出。同级目录下有日志文件，也许会有错误详情。如果真是这个原因，可能是API失效或者网络问题，我会去排查一下API。

**Comment by XJChenYang** [comment]
[CCTVVideoDownloader.log](https://github.com/user-attachments/files/16131062/CCTVVideoDownloader.log)

**Comment by letr007** [comment]
从日志来看，每当在请求API获取节目列表时闪退，可能是API或网络的问题，我去排查下API

**Comment by letr007** [comment]
排查过了，API仍能够正常使用，可能为网络问题。
```cmd
curl -H "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0" -G -d "id=TOPC1451559180488841" -d "n=5" -d "sort=desc" -d "p=1" -d "mode=0" -d "serviceId=tvcctv" https://api.cntv.cn/NewVideo/getVideoListByColumn?
```
在命令行中执行上述代码，如果有正常输出则代表能够访问央视网的API，那就可能是其他问题，如果没有正常输出，那么就是网络问题所致。

**Comment by letr007** [comment]
能否详细说明一下，导入的视频链接？

**Comment by quanbaba113** [comment]
我这也有遇到类似闪退的问题，V3.0.0和V3.1.0都有类似闪退问题

测试环境：
Win10企业版22H2

测试步骤：
1、节目-导入节目
2、点击所成功添加的"节目信息"下的名称或ID，出现闪退

测试视频链接1：
https://tv.cctv.com/2012/10/07/VIDE1355149825921114.shtml

说明：
此链接必现闪退

测试视频链接2：
https://tv.cctv.com/2024/07/25/VIDEX5L3AyPMw6tK1OpZC4da240725.shtml
https://tv.cctv.com/2024/07/25/VIDEX5L3AyPMw6tK1OpZC4da240725.shtml
https://tv.cctv.com/2024/07/22/VIDEGbvH382JhuqsfyMmtI3I240722.shtml

说明：
依次导入添加上述多个视频，随意点击所成功添加的"节目信息"下某个名称或ID，出现闪退

**Comment by letr007** [comment]
感谢反馈，从复现结果来看，是对链接返回数据的格式化处理出现了问题

**Comment by letr007** [comment]
出现问题的链接导入的都是纪录片，分析后发现，纪录片与正常栏目使用的API不同，获取节目相关信息调用的不是同一套API，使用栏目的API去获取纪录片信息就会返回错误信息，因而出现数据格式化错误。
感谢反馈，以后可能会增加纪录片相关的适配

**Comment by quanbaba113** [comment]
好的，感谢大佬回复！
