### ISSUE TITLE
下载新闻联播的时候因为标题里的冒号会导致异常

### ISSUE THREAD

**Issue by zestybaby** [letr007/CCTVVideoDownloader#12]
下载的时候没有问题，但是在生成文件时文件名会停在冒号之前的部分，生成的文件也只有空白。

**Comment by letr007** [comment]
感谢反馈，如果能有截图可以更快debug

**Comment by hsh241817** [comment]
这是由于windows文件命名规范造成的，冒号在规范中属于非法字符，导致文件名无效
修改意见：在video_process.py文件中添加

illegal_chars_pattern = r'[\\/:*?"<>|]'  # 匹配非法字符
        filename = re.sub(illegal_chars_pattern, '', self.name)
        output_path = fr'{self.save_path}\{filename}.mp4'
        
command = [f'{ffmpeg_path}', '-f', 'concat', '-safe', '0', '-i', fr'{path}\video_list.txt', '-c', 'copy',
                       '-y', output_path]            # 使用 subprocess 调用 ffmpeg，并设置 creationflags 参数
