### ISSUE TITLE
报错：错误详情:'CCTVVideoDownload' object has no attribute 'choise_id'

### ISSUE THREAD

**Issue by Liu8Can** [letr007/CCTVVideoDownloader#2]
[节目信息]节目信息重载完成
[视频信息]获取列表...
[ERROR]在获取视频信息时出现错误 错误详情:'CCTVVideoDownload' object has no attribute 'choise_id'

-------------------------------------------------------

经测试发现即使使用仓库中的cdi文件示例依然会报相同的错误，经测试排除了文件编码和代理的原因，具体原因未知。
目标网址：https://gongyi.cctv.com/2023/06/11/VIDEsxu1eRWHfNCiPsFk60nc230611.shtml
id通过网页抓取获得的

**Comment by Liu8Can** [comment]
后发现配置文件信息必须改成“config”就可正常读到了。但目标网址仍然无法正常下载：报错[ERROR]在获取视频信息时出现错误 错误详情:'data'。
可能因为我的链接是个单p视频吧

**Comment by letr007** [comment]
这个是只适用于像新闻周刊这种的系列的视频的，关于配置文件的问题，以后会进行修改。
id是需要自己去抓取的，确实有点麻烦，也许以后会进行优化。
这个项目的结构有点混乱，以后会进行重构，在重构之前将不在更新。由于某些原因，重构可能会在7月份进行。
