### ISSUE TITLE
如何获取id呢

### ISSUE THREAD

**Issue by jyjxqy** [letr007/CCTVVideoDownloader#3]
这个id应该怎么爬到呢，一个节目对应一个id么，应该去哪里找呢

**Comment by letr007** [comment]
![image](https://github.com/letr007/CCTVVideoDownload/assets/123731298/ca723bdd-a6cc-4a70-bf6e-85a701c9e93f)
是的，一个节目对应一个ID标识。
目前暂时没有添加ID获取功能，ID还需要手动获取。
获取后按照配置文件的json格式添加新节目即可。
