### ISSUE TITLE
怎么找到不加密通道

### ISSUE THREAD

**Issue by myfymyfy** [letr007/CCTVVideoDownloader#5]
大佬好，我用了你的程序，能够爬下来央视的视频。
我在下载视频的ui里看到你是通过这个网址下载的https://newcntv.qcloudcdn.com/asp/hls/1200/0303000a/3/default/
我尝试过自己爬取央视视频，但爬下来的ts都是加密的。
我学习一下你是如何找到这个网址的

**Comment by myfymyfy** [comment]
我想学习一下你找到这个不加密网址的过程

**Comment by letr007** [comment]
> 我想学习一下你找到这个不加密网址的过程

可以去看一下src里面的Dlhandle.py，对于m3u8的抓取与处理都封装在里面，可以参考一下。注意爬下来的main.m3u8，里面有指向其他m3u8文件的链接，非加密的，可以参照项目源码解析一下，最终是可以找到源文件的。大佬这个称呼真的担当不起，也是边学边做的这个项目，代码也是写的一塌糊涂。
