### ISSUE TITLE
视频下载问题

### ISSUE THREAD

**Issue by NnoTeam** [letr007/CCTVVideoDownloader#7]
由于工作上需要用到CCTV的视频，所以我用控制台调试，找到了m3u8的链接，我用ffmpeg下载，但是下载好的视频却是乱码
**命令**
ffmpeg -i https://dh5.cntv.myhwcdn.cn/asp/h5e/hls/2000/0303000a/3/default/${guid}/2000.m3u8 -c copy new.mp4
**结果**
![image](https://github.com/letr007/CCTVVideoDownload/assets/172319011/d3fae477-8f27-4d69-8910-6263eef36bfb)
求大佬教一教，是视频加密的原因吗？

**Comment by letr007** [comment]
直接抓出来的m3u8确实是加密的.
直接找视频播放节目的m3u8我们没有其对应的解密方法.
我是从另一个方面找的，访问https://[vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid={guid}](https://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid=230e579a10f14ab18ad0ce407964a9cb)(这里以新闻周刊为例)可以得到返回数据，在其中有"hls_url"字段([链接](https://newcntv.qcloudcdn.com/asp/hls/main/0303000a/3/default/230e579a10f14ab18ad0ce407964a9cb/main.m3u8?maxbr=2048))，访问其链接可以得到一个m3u8文件，但这个文件中不包含正常可播放的内容，仅提供了一个相对链接(/asp/hls/450/0303000a/3/default/230e579a10f14ab18ad0ce407964a9cb/450.m3u8)，这个链接与"hls_url"的域名(https://newcntv.qcloudcdn.com)拼接在一起访问才可得到真正的未加密的m3u8文件[链接](https://newcntv.qcloudcdn.com/asp/hls/450/0303000a/3/default/230e579a10f14ab18ad0ce407964a9cb/450.m3u8)，此时再用ffmpeg即可正常下载.

**Comment by letr007** [comment]
![image](https://github.com/letr007/CCTVVideoDownload/assets/123731298/f352f65b-af56-4c89-bd40-4cdf175773d6)
访问hls_url得到的m3u8文件
![image](https://github.com/letr007/CCTVVideoDownload/assets/123731298/24aa5815-eb43-42cc-97b8-526279b256fb)

**Comment by letr007** [comment]
大佬我担当不起，只是没事写着玩而已qwq

**Comment by NnoTeam** [comment]
谢谢大佬愿意花时间写这么多文字，感激不尽！
