### ISSUE TITLE
cctvdownload一直合并，没有视频

### ISSUE THREAD

**Issue by Maxzby** [letr007/CCTVVideoDownloader#8]
你好作者，我使用最新版本的cctvvideodownload一直显示合并中，没有视频，cdi用的是你文档下面提供的
系统是windows11 22h2，并使用管理员模式运行，但依然无法使用

**Comment by Maxzby** [comment]
> 你好作者，我使用最新版本的cctvvideodownload一直显示合并中，没有视频，cdi用的是你文档下面提供的 系统是windows11 22h2，并使用管理员模式运行，但依然无法使用

**Comment by Maxzby** [comment]
![屏幕截图 2024-06-23 111532.png](https://s2.loli.net/2024/06/23/McVDSX3COAy7LUB.png)

**Comment by letr007** [comment]
不好意思，用的打包工具的问题，这个打包工具添加环境变量的脚本可能没有成功执行，建议去手动检查一下ffmpeg是否在环境变量path中。
项目正在重构，新版本会解决这个问题。

**Comment by Maxzby** [comment]
你好，作者大大，path中有ffmpeg，但是c盘里面ffmpeg并没有解压出来
![屏幕截图 2024-06-23 134832.png](https://s2.loli.net/2024/06/23/gltdyMN3GPSn6ou.png)

**Comment by Maxzby** [comment]
你好，作者大大，我使用[CODEX FFMPEG](https://www.gyan.dev/ffmpeg/builds/)的Full版本的ffmpeg7.0.1放在C:\ffmpeg\bin，依然没用，CCTVvideodownload下完合成的时候，会弹出ffmpeg的命令提示符，然后闪退，一直卡正在合成，换成essentials版本的ffmpeg也一样，会闪退，系统变量也设置了，管理员运行也试了，都不行
![屏幕截图 2024-06-23 142234.png](https://s2.loli.net/2024/06/23/jGSekH5OCrZxVEB.png)

**Comment by letr007** [comment]
好的。去找一下以前版本的release其中有ffmpeg，如果还是不行的话应该就是在win11上出现bug了，此版本是在win10环境开发的，没有在win11环境测试过。
重构的新版本中会考虑这个问题，感谢反馈。

**Comment by letr007** [comment]
暂时没有什么好的解决办法，抱歉

**Comment by Maxzby** [comment]
好的，我现在去尝试

**Comment by Maxzby** [comment]
没关系的，开源的意义就是和作者发现问题，修复问题，我发现不管是windows11还是windows10下，下载视频都是0进度，c盘的ctvd_tmp文件夹也是空的，软件并没有正常下载，网络正常，电信宽带，可以正常访问cctv，代理已关，依然0%
![无标题.png](https://s2.loli.net/2024/06/23/WQTrKo4EvMsLen2.png)

**Comment by letr007** [comment]
代码重构工作即将完成，新版本将于不久后发布，到时候这些问题都会解决的

**Comment by letr007** [comment]
下载没有视频的原因找到了，api失效了，央视网采取措施封禁了现在所使用的视频获取方法。
